# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    params:
        website:
         #  title : AGORA Ex Machina ou bien non?
         #  version : v0.9.2
            language : fr
         #  name : CRLBazin
            lang : fr_FR
            ecriture : ltr
         #   administrator:
         #       email: crlbazin@gmail.com
                
    themes_images_directory: '/public/img/upload/themes'
    workshops_images_directory: '/public/img/upload/workshops'
    workshops_documents_directory: '/public/pdf/upload/workshops'
    users_images_directory: '/public/img/upload/users'
    wallpapers_images_directory: '/public/img/upload/wallpapers'
    categories_images_directory: '/public/img/upload/categories'

    # ici vos autres variables
    app.locales: [en, fr]
    app.app_env: '%env(APP_ENV)%'
    app.smtp_email: '%env(MAILER_DSN)%'



services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Twig\TwigGlobalSubscriber:
